### PR TITLE
Only add the -M flag when filter includes renames

### PR DESCRIPTION
**Pull request by twhitbeck**
This seemed like an obvious optimization...

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@twhitbeck - is the idea here that passing `-M` to git will slow it down and so we should only pass it when needed?

**Comment by mcwhittemore** [comment]
also, @twhitbeck - I just added circleci to this repo, can you rebase on master and push so the tests will auto run?

**Comment by twhitbeck** [comment]
I merged master into this branch. Does that work? Or should I rebase and create a new PR?
Yes, the idea is to avoid incurring any cost of the `-M` flag unless renames are actually going to be reported.

**Comment by mcwhittemore** [comment]
Hmm... I that would trigger the tests to run on circleci, but it didn't. I've run locally and all it well.

**Pull request merged**
